name: Deploy Service

on:
  push:
    branches:
      - main

jobs:
  deploy-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 117.72.122.27 >> ~/.ssh/known_hosts

    - name: Deploy Service to Server
      run: |
        scp -r service/* deployer@117.72.122.27:/www/wwwroot/default/service
        ssh deployer@117.72.122.27 "cd /www/wwwroot/default/service && yarn install && pm2 restart service"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
